instalacion depende.. pip install fastapi-utils
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed.
This behaviour is the source of the following dependency conflicts.
pydantic-settings 2.0.3 requires pydantic>=2.0.1, but you have pydantic 1.10.13 which is incompatible.